"""Compile a `.gitinclude` declaration into the root `.gitignore` gr2 owns.

Ignore by default, `.gitinclude` names what is tracked (Layne, 2026-09-23). The
declaration's SENSE is gitignore's inverted: a plain pattern INCLUDES, and a `!`
pattern IGNORES within what was included.

CANONICAL FORMS ONLY, EVERYTHING ELSE REPORTED, and the OUTPUT IS CANONICAL TOO.
Three properties hold by construction rather than case by case, and each has a
witness with a mutation control in the tests:

1. THE COMPILE IS PURE TEXT. It never asks whether a path is a file or a
   directory. Every accepted path emits `!/p` and `!/p/**`, which covers both:
   for a file the glob line matches nothing, for a directory it is what makes the
   contents visible. A compiler that consulted the tree would emit different
   bytes for a fresh clone and a materialized desk, and both files would look
   reasonable.

2. THE OUTPUT IS ORDER-INDEPENDENT. Includes are emitted first, then ignores,
   each group sorted by path. Git resolves ignore rules by the LAST matching
   line, so emitting ignores last is what makes an ignore always win regardless
   of where it was written; sorting is what makes two declarations that differ
   only in line order compile to the same bytes. The first version emitted in
   declaration order, and `!docs/secret.txt` written ABOVE `docs/` silently
   tracked the file it was written to exclude.

3. A CONFLICT IS REPORTED, NOT SILENT. An include at or under an ignored path
   can never take effect, because the ignore is emitted last and wins. That is
   reported as a conflict: the line is emitted, and it will not do what it says.

Accepted forms, each optionally prefixed with `!`:

    # comment             blank lines            (emitted: nothing)
    README.md             a literal path
    docs/guide/a.md       a literal path, nested
    docs/                 a literal path, trailing slash allowed and STRIPPED

Refused and reported, with nothing emitted:

    a leading `/`         paths are already relative to the workspace root
    *  ?  [  ]            glob metacharacters
    **                    a glob
    \\                    a backslash escape
    .  or  ..             as a path SEGMENT, never as a leading dot: `.github/`
                          and `.env` are ordinary names and stay acceptable
    //                    an empty path segment
    !.gitinclude          the declaration is always tracked, so an ignore for it
                          is refused rather than silently defeating that line

A trailing slash is stripped rather than kept, so `README.md/` tracks the file
`README.md` instead of matching only directories and dropping it silently, and
`docs/` and `docs` emit identical lines.
"""
from __future__ import annotations

from dataclasses import dataclass

SELF = "/.gitinclude"

HEADER = (
    "# Generated by gr2 from .gitinclude -- do not edit.\n"
    "# Ignore by default; the declaration names what is tracked.\n"
)

_METACHARS = {
    "*": "a glob metacharacter",
    "?": "a glob metacharacter",
    "[": "a glob metacharacter",
    "]": "a glob metacharacter",
    "\\": "a backslash escape",
}

REFUSED = "refused"
CONFLICT = "conflict"


@dataclass(frozen=True)
class Notice:
    """One thing the user needs to know about their declaration.

    `kind` is REFUSED (the line is not accepted and nothing is emitted for it) or
    CONFLICT (the line IS emitted, but an ignore at or above it wins, so it will
    not do what it says). The two are different outcomes and the caller prints
    them differently, so they are not collapsed into one list of strings.
    """

    line: str
    reason: str
    kind: str


def _normalise(body: str) -> str | None:
    """The path as it will be emitted, or None when a rule refuses it.

    The refusal itself is raised by the caller so it can name the ORIGINAL line,
    which is what the user has to go and edit.
    """
    return body.rstrip("/")


def _refusal_reason(body: str) -> str | None:
    if not body:
        return "an empty pattern"
    if body.startswith("/"):
        return "a leading slash is not accepted; paths are relative to the root"
    for char, why in _METACHARS.items():
        if char in body:
            return f"{why}: {char!r}"
    if "//" in body:
        return "an empty path segment (`//`)"
    segments = body.rstrip("/").split("/")
    if any(seg in (".", "..") for seg in segments):
        return "a `.` or `..` path segment"
    return None


def _lines_for(path: str, prefix: str, with_ancestors: bool) -> list[str]:
    """The anchored lines one accepted path needs, ancestors before the entry.

    The trailing slash is already stripped by the caller, so the entry line
    matches a file and a directory alike.
    """
    segments = path.split("/")
    out: list[str] = []
    if with_ancestors:
        out.extend(
            f"{prefix}/{'/'.join(segments[: i + 1])}/"
            for i in range(len(segments) - 1)
        )
    out.append(f"{prefix}/{path}")
    out.append(f"{prefix}/{path}/**")
    return out


def compile_gitignore(text: str) -> tuple[str, list[Notice]]:
    """Compile `.gitinclude` text into the `.gitignore` gr2 writes.

    Returns the generated text and the report. The report is part of the API
    rather than a side channel: the caller prints it, so a line that is refused,
    or that a later ignore will defeat, is visible to the person who wrote it
    instead of quietly doing nothing.
    """
    includes: list[str] = []
    ignores: list[str] = []
    report: list[Notice] = []

    for raw in text.splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        is_ignore = line.startswith("!")
        body = line[1:].strip() if is_ignore else line
        reason = _refusal_reason(body)
        if reason is not None:
            report.append(Notice(line=raw, reason=reason, kind=REFUSED))
            continue
        path = _normalise(body)
        assert path is not None
        if is_ignore and path.casefold() == ".gitinclude":
            # The declaration is always tracked, and this file emits that line
            # itself. An ignore for it would be emitted LAST and defeat it, with
            # an empty report, so it is refused instead of silently winning.
            # The comparison is fold-cased (measured on APFS, where git folds paths):
            # folds paths when the host's core.ignorecase is true, so a case
            # variant of the declaration's name defeats the self line exactly
            # like the exact spelling, and silently. Still pure text: casefold
            # consults no filesystem.
            report.append(
                Notice(
                    line=raw,
                    reason=(
                        "the declaration is always tracked, so it cannot be ignored"
                    ),
                    kind=REFUSED,
                )
            )
            continue
        (ignores if is_ignore else includes).append(path)

    # An include at or under an ignored path can never take effect: the ignore is
    # emitted last and git resolves by the last matching line. Report it rather
    # than let it look tracked. The comparison is fold-cased (measured: on a
    # case-insensitive host git folds the emitted lines too, so an include that
    # differs from its ignore only by case is defeated exactly like one that
    # matches exactly, and the report must say so. The notice names the lines as
    # written, and `docs2` still does not conflict with `!docs` — the segment
    # boundary survives the fold.
    for inc in includes:
        inc_fold = inc.casefold()
        for ign in ignores:
            ign_fold = ign.casefold()
            if inc_fold == ign_fold or inc_fold.startswith(ign_fold + "/"):
                report.append(
                    Notice(
                        line=inc,
                        reason=(
                            f"ignored by `{ign}`, so this include cannot take effect"
                        ),
                        kind=CONFLICT,
                    )
                )
                break

    lines = ["*", f"!{SELF}"]
    for path in sorted(set(includes)):
        lines.extend(_lines_for(path, "!", with_ancestors=True))
    # Emitted after the includes, sorted: this is what makes an ignore always win
    # and two orderings of one declaration compile to the same bytes.
    for path in sorted(set(ignores)):
        lines.extend(_lines_for(path, "", with_ancestors=False))
    return HEADER + "\n".join(lines) + "\n", report
