"""A plain recursive clone of a native store fills its members at their pins.

THE DEFECT, measured on dev 807f9ec6: a native store records each member as a mode 160000 gitlink and its origin
in `grip.toml`, but writes no `.gitmodules`, so `git clone --recurse-submodules <root>` exits 0 and leaves every
member directory EMPTY, and `git add <member>` prints "adding embedded git repository" once per member. Git only
knows where a gitlink comes from through `.gitmodules`.

THE SPECIFIED SHAPE: gr2 generates `.gitmodules` from `grip.toml` (each member's path and origin URL) and never
hand-keeps it, so a plain recursive clone fills the members and the two files cannot drift.

Fixtures are real git with bare local origins and no network. Git's default protocol rules refuse a local-path
submodule URL (`protocol.file.allow`), so the clone rows name that setting; the row that omits it records what a
reader without it meets.
"""
from __future__ import annotations

import subprocess
from pathlib import Path

from tests.test_store_git_hooks import _advance, _gitlink, _store, _with_root_origin
from tests.test_store_git_native_smoke import git, gr2

MEMBERS = ("alpha", "beta")


def _published_root(tmp_path: Path) -> tuple[Path, Path]:
    """A store with one recorded root commit, pushed to a bare origin."""
    root = _store(tmp_path)
    bare = _with_root_origin(tmp_path, root)
    pushed = git(root, "push", "origin", "main", check=False)
    assert pushed.returncode == 0, f"{pushed.stdout}\n{pushed.stderr}"
    return root, bare


def _recursive_clone(tmp_path: Path, bare: Path, *, allow_file: bool) -> tuple[Path, subprocess.CompletedProcess[str]]:
    dest = tmp_path / "clone"
    allow = ["-c", "protocol.file.allow=always"] if allow_file else []
    result = subprocess.run(
        ["git", *allow, "clone", "--recurse-submodules", str(bare), str(dest)], capture_output=True, text=True
    )
    return dest, result


def _checkout_state(dest: Path, member: str) -> tuple[bool, str]:
    """(is its own checkout, HEAD) for one member directory of the clone."""
    work = dest / member
    top = subprocess.run(["git", "-C", str(work), "rev-parse", "--show-toplevel"], capture_output=True, text=True)
    own = top.returncode == 0 and Path(top.stdout.strip()).resolve() == work.resolve()
    head = subprocess.run(["git", "-C", str(work), "rev-parse", "HEAD"], capture_output=True, text=True).stdout.strip()
    return own, head if own else ""


def test_a_recursive_clone_of_the_store_fills_every_member_at_its_pin(tmp_path: Path) -> None:
    root, bare = _published_root(tmp_path)

    dest, cloned = _recursive_clone(tmp_path, bare, allow_file=True)

    assert cloned.returncode == 0, f"{cloned.stdout}\n{cloned.stderr}"
    for member in MEMBERS:
        own, head = _checkout_state(dest, member)
        assert own, f"{member} is not a checkout in the clone (.gitmodules in the clone: {(dest / '.gitmodules').exists()})"
        assert head == _gitlink(root, member), f"{member} is not at its pin"


def _generated(root: Path) -> str:
    from gr2.python_cli.grip_cli import _native_members, render_gitmodules

    return render_gitmodules(_native_members(root))


def test_the_recorded_gitmodules_is_what_grip_toml_generates(tmp_path: Path) -> None:
    root = _store(tmp_path)

    recorded = git(root, "show", "HEAD:.gitmodules").stdout

    assert recorded == _generated(root)
    assert recorded.startswith("# generated by gr2 from grip.toml")
    for member in MEMBERS:
        assert f'[submodule "{member}"]' in recorded and f'path = "{member}"' in recorded


def test_a_plain_git_commit_restores_a_deleted_gitmodules(tmp_path: Path) -> None:
    root = _store(tmp_path)
    git(root, "rm", "-q", "-f", ".gitmodules")
    git(root, "commit", "-q", "--no-verify", "-m", "someone removed it")
    assert git(root, "ls-tree", "HEAD", "--", ".gitmodules").stdout.strip() == ""

    committed = git(root, "commit", "--allow-empty", "-m", "plain commit", check=False)

    assert committed.returncode == 0, f"{committed.stdout}\n{committed.stderr}"
    assert git(root, "show", "HEAD:.gitmodules").stdout == _generated(root)


def test_a_plain_git_commit_rewrites_a_hand_edited_gitmodules(tmp_path: Path) -> None:
    root = _store(tmp_path)
    working = root / ".gitmodules"
    working.write_text(working.read_text().replace('path = "alpha"', 'path = "elsewhere"'))
    git(root, "add", "-f", ".gitmodules")

    committed = git(root, "commit", "-m", "hand edit", check=False)

    assert committed.returncode == 0, f"{committed.stdout}\n{committed.stderr}"
    assert git(root, "show", "HEAD:.gitmodules").stdout == _generated(root)
    assert "elsewhere" not in git(root, "show", "HEAD:.gitmodules").stdout


def test_a_gitmodules_gr2_did_not_write_is_left_alone_and_the_commit_still_succeeds(tmp_path: Path) -> None:
    """An adopted superproject carries its own `.gitmodules`. gr2 generates nothing beside it and does not refuse the
    commit; refusing would make every `store commit` in such a root fail."""
    root = _store(tmp_path)
    theirs = '[submodule "other"]\n\tpath = other\n\turl = https://example.test/other.git\n'
    (root / ".gitmodules").write_text(theirs)
    git(root, "add", "-f", ".gitmodules")
    git(root, "commit", "-q", "--no-verify", "-m", "an owner's own file")
    moved = _advance(root, "alpha", push=True)

    committed = gr2(root, "commit", "-m", "again", check=False)

    assert committed.returncode == 0, f"{committed.stdout}\n{committed.stderr}"
    assert _gitlink(root, "alpha") == moved
    assert (root / ".gitmodules").read_text() == theirs
    assert git(root, "show", "HEAD:.gitmodules").stdout == theirs


def test_a_plain_git_commit_leaves_a_foreign_gitmodules_alone(tmp_path: Path) -> None:
    root = _store(tmp_path)
    theirs = '[submodule "other"]\n\tpath = other\n\turl = https://example.test/other.git\n'
    (root / ".gitmodules").write_text(theirs)
    git(root, "add", "-f", ".gitmodules")

    committed = git(root, "commit", "-m", "adopt the owner's file", check=False)

    assert committed.returncode == 0, f"{committed.stdout}\n{committed.stderr}"
    assert git(root, "show", "HEAD:.gitmodules").stdout == theirs


def test_without_the_file_protocol_setting_a_local_path_clone_leaves_members_empty(tmp_path: Path) -> None:
    """The control for the recursive-clone row: git's own default refuses a local-path submodule URL, so a reader who
    does not name `protocol.file.allow` gets an empty member and a message from git, not a fill. A real remote (https)
    is not affected; this fixture is local only."""
    _root, bare = _published_root(tmp_path)

    dest, cloned = _recursive_clone(tmp_path, bare, allow_file=False)

    assert not _checkout_state(dest, "alpha")[0]
    assert "protocol" in (cloned.stdout + cloned.stderr).lower() or cloned.returncode != 0, cloned.stderr


def test_a_second_store_commit_after_a_member_moves_keeps_the_generated_gitmodules(tmp_path: Path) -> None:
    """The declaration never lists `.gitmodules`, and it is in the index from the first commit on. A coverage check
    that treated it like an owner's path would refuse every later commit."""
    root = _store(tmp_path)
    moved = _advance(root, "alpha", push=True)

    second = gr2(root, "commit", "-m", "second", check=False)

    assert second.returncode == 0, f"{second.stdout}\n{second.stderr}"
    assert _gitlink(root, "alpha") == moved
    assert git(root, "show", "HEAD:.gitmodules").stdout == _generated(root)


_THEIRS = '[submodule "other"]\n\tpath = other\n\turl = https://example.test/other.git\n'
_NAMED = ".gitmodules exists and is not gr2's, so a recursive clone will not fill from grip.toml"


def test_store_status_and_init_name_a_foreign_gitmodules(tmp_path: Path) -> None:
    """Leaving the owner's file alone is right, but silence would leave the recursive-clone gap unexplained."""
    root = _store(tmp_path)
    (root / ".gitmodules").write_text(_THEIRS)
    git(root, "add", "-f", ".gitmodules")
    git(root, "commit", "-q", "--no-verify", "-m", "an owner's own file")

    status = gr2(root, "status", check=False)
    init = gr2(root, "init", check=False)

    assert _NAMED in status.stderr, f"{status.stdout}\n{status.stderr}"
    assert _NAMED in init.stderr, f"{init.stdout}\n{init.stderr}"


def test_store_status_and_init_are_silent_about_a_gitmodules_gr2_wrote(tmp_path: Path) -> None:
    """The control: the same verbs on an ordinary store print no such line, so the row above is not a banner."""
    root = _store(tmp_path)

    status = gr2(root, "status", check=False)
    init = gr2(root, "init", check=False)

    assert ".gitmodules" not in status.stderr, status.stderr
    assert ".gitmodules" not in init.stderr, init.stderr
